spring:
  cache:
    type: redis
    redis:
      time-to-live: ${ROUTE_CACHE_TTL_MS:600000}
      cache-null-values: false

  datasource:
    url: jdbc:postgresql://route-db:5432/route_db
    username: postgres
    password: 5558
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  redis:
    host: redis
    port: 6379
    timeout: 6000

  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8082

services:
  poi:
    base-url: http://poi-service:8081/api/poi
  auth:
    url: http://auth-service:8084/api
    me-path: /internal/users/me
    info-path: /internal/users/{id}/info
    exists-path: /internal/users/{id}/exists

logging:
  level:
    com.travelapp.route: INFO
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always