spring:
  datasource:
    url: jdbc:postgresql://poi-db:5432/poi_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  # Redis как кеш (в docker-профиле)
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

  redis:
    host: redis
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

services:
  city:
    base-url: http://city-service:8082/api/cities
  auth:
    base-url: http://auth-service:8084/api/auth
  review:
    base-url: http://review-service:8083/api/review