spring:
  cache:
    type: redis
    redis:
      time-to-live: ${POI_CACHE_TTL_MS:600000}
      cache-null-values: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
