spring:
  datasource:
    url: jdbc:postgresql://review-db:5432/travel_review_db
    username: postgres
    password: 1234

service:
  auth:
    url: http://auth-service:8084/api
  poi:
    url: http://poi-service:8081/api/poi