spring:
  datasource:
    url: jdbc:postgresql://review-db:5432/travel_review_db
    username: postgres
    password: 1234

  # если решишь всё-таки кэшировать отзывы через redis:
  # cache:
  #   type: redis
  # redis:
  #   host: redis
  #   port: 6379

service:
  auth:
    url: http://auth-service:8084/api/auth
  poi:
    url: http://poi-service:8081/api/poi
  notification:
    url: http://notification-service:8085/api/notifications